// Exact generated documents from the previous portfolio catalog.
export default {
  "/home/ibrahim/Projets/LearnXcompile/README.md": "# LearnXcompile\n\nLa présentation détaillée de LearnXcompile sera ajoutée avec la documentation du projet.\n\nProjet principal · Présentation en préparation\n\nPrésentation détaillée en préparation.\n\n## Sources\nCV d’Ibrahim Chehlafi\n",
  "/home/ibrahim/Projets/ParcVision/README.md": "# ParcVision\n\nUne plateforme métier qui réunit gestion de flotte automobile et archivage intelligent des documents.\n\n## Technologies\nJava · Spring Boot · PostgreSQL · Tesseract OCR · Leaflet\n\n## Fonctionnalités\n- Gestion des véhicules, conducteurs, missions et maintenance\n- Archivage GED et recherche dans le texte extrait par OCR\n- Authentification Spring Security / JWT avec cookies HttpOnly\n- Tableaux de bord et simulation GPS interactive avec Leaflet\n\n## Code source\nhttps://github.com/ibrahim11-dv/ParcVision-StageTech\n",
  "/home/ibrahim/Projets/MiniChat/README.md": "# MiniChat\n\nUne application de messagerie construite autour d’un client React et d’un serveur Socket.io.\n\n## Technologies\nReact · Node.js · Express · Socket.io · Vite\n\n## Fonctionnalités\n- Architecture séparant le client et le serveur\n- Communication par sockets avec Socket.io\n- Interface React et environnement Vite\n\n## Code source\nhttps://github.com/ibrahim11-dv/MiniChatApp-using-socket.io\n",
  "/home/ibrahim/Projets/ParcVision Mobile/README.md": "# ParcVision Mobile\n\nLe volet Android du projet ParcVision, réalisé en Java avec les composants Material.\n\n## Technologies\nAndroid · Java · Gradle · Material Design\n\n## Fonctionnalités\n- Projet Android natif en Java\n- Composants AndroidX et Material\n- Module mobile associé au projet de stage ParcVision\n\n## Code source\nhttps://github.com/ibrahim11-dv/ParcVisionMobile-StageTech\n",
  "/home/ibrahim/Projets/Exercise Tracker/README.md": "# Exercise Tracker\n\nUne API de suivi des exercices réalisée dans le cadre du parcours Backend de freeCodeCamp.\n\n## Technologies\nNode.js · Express · API REST\n\n## Fonctionnalités\n- Création d’utilisateurs et enregistrement d’exercices\n- Historique filtré par période et limite de résultats\n- Réponses JSON et endpoints REST\n\n## Code source\nhttps://github.com/ibrahim11-dv/exerciceTracker-freeCodeCamp_\n",
  "/home/ibrahim/Projets/URL Shortener/README.md": "# URL Shortener\n\nUn microservice Express qui transforme une URL en identifiant court et redirige vers l’adresse d’origine.\n\n## Technologies\nNode.js · Express · JavaScript\n\n## Fonctionnalités\n- Validation des URL HTTP et HTTPS\n- Création d’identifiants courts via API\n- Redirection vers l’URL d’origine\n\n## Code source\nhttps://github.com/ibrahim11-dv/url-shortening\n"
};
