// Editorial reports grounded in the supplied CV and the linked repository files.
export const PROJECTS = [
  {
    id: 'parcvision', name: 'ParcVision', group: 'main', category: 'Application métier', accent: '#e99756', visual: 'fleet',
    tagline: 'Une flotte. Tous ses mouvements.', context: 'Stage · ZAI-CONCEPT INFO', period: 'Avril – juin 2026',
    role: 'Développement full-stack · stage', status: 'Projet de stage', technicalFocus: 'Gestion métier, sécurité, OCR et cartographie', evidence: 'README et code source public inspectés',
    description: 'Gestion de flotte automobile et archivage intelligent, réunis dans une application web.',
    stack: ['Java', 'Spring Boot', 'Spring Security', 'PostgreSQL', 'Tesseract OCR', 'Leaflet'],
    github: 'https://github.com/ibrahim11-dv/ParcVision-StageTech',
    highlights: ['Véhicules, conducteurs, missions et maintenance', 'Archivage documentaire et recherche dans le texte extrait', 'Authentification JWT avec cookies HttpOnly', 'Cartographie Leaflet et simulation GPS'],
    report: {
      intro: 'Un véhicule est aussi un ensemble de missions, de dépenses, de documents et d’interventions. ParcVision rassemble ces informations pour donner une vue cohérente de l’activité d’une flotte.',
      problem: 'La gestion quotidienne demande de relier des informations très différentes : disponibilité des conducteurs, état des véhicules, assurance, maintenance et documents justificatifs. Le projet répond à ce besoin de centralisation dans le cadre de mon stage chez ZAI-CONCEPT INFO à Errachidia.',
      solution: 'L’application organise le travail autour d’un espace d’administration. Les véhicules et conducteurs alimentent la préparation des missions ; les interventions et incidents enrichissent leur historique. Les dépenses et indicateurs apportent une lecture transversale de l’activité. La GED complète cette gestion avec une arborescence documentaire et une recherche par nom ou contenu.',
      architecture: [
        ['Interface web', 'HTML, CSS, JavaScript et Bootstrap composent les écrans métier ; Leaflet affiche les parcours sur une carte.'],
        ['Services métier', 'Les contrôleurs Spring exposent les opérations. Les services portent les traitements de flotte, de mission et d’archivage.'],
        ['Données & documents', 'Spring Data JPA relie les entités à PostgreSQL. Tess4J s’appuie sur Tesseract pour extraire le texte des documents numérisés.'],
      ],
      decisions: [
        ['Séparer les responsabilités', 'Une architecture N-tier répartit interface, logique métier et persistance afin de garder les opérations du domaine distinctes des écrans.'],
        ['Rendre les archives consultables', 'L’extraction OCR asynchrone permet une recherche dans le contenu des images et PDF numérisés, avec des extraits de contexte.'],
        ['Distinguer simulation et télémétrie', 'Le dépôt présente un suivi GPS simulé. La carte illustre les trajets et les positions ; elle ne prouve pas un raccordement à des boîtiers GPS réels.'],
      ],
      outcome: 'Le projet réunit deux domaines complémentaires : les opérations d’une flotte et leurs pièces documentaires. Il illustre mon travail sur une application métier structurée, de l’authentification à la visualisation cartographique et au traitement de documents.',
      boundaries: 'Le dépôt fournit des données de démonstration et une simulation GPS. Aucun chiffre de performance ou de fréquentation n’est revendiqué ici.',
      steps: [
        { title: 'Préparer une mission', label: 'Véhicule + conducteur', text: 'Associer un véhicule et un conducteur à un trajet, puis préciser les instructions et la cargaison.', output: 'Mission préparée' },
        { title: 'Suivre le parcours', label: 'Carte interactive', text: 'Visualiser le trajet, les points de passage et la position simulée sur une carte Leaflet.', output: 'Parcours visualisé' },
        { title: 'Relier les documents', label: 'GED + OCR', text: 'Classer une pièce numérisée et rendre son texte consultable grâce à Tesseract.', output: 'Archive consultable' },
      ],
      sources: [{ label: 'Présentation et architecture', path: 'README.md' }],
    },
  },
  {
    id: 'pfe-esto', name: 'PFE-ESTO', group: 'main', category: 'Application métier', accent: '#a99cec', visual: 'campus',
    tagline: 'Le parcours académique, connecté.', context: 'Projet de fin d’études · ESTO', period: '2025 – 2026',
    role: 'Projet de fin d’études · travail collaboratif', status: 'Projet de fin d’études', technicalFocus: 'Portail multi-rôles et données académiques', evidence: 'CV et routes publiques du dépôt inspectés',
    description: 'Un portail académique multi-rôles pour les notes, les modules et le suivi pédagogique.',
    stack: ['PHP', 'Laravel', 'Eloquent', 'Blade', 'MySQL', 'RBAC'], github: 'https://github.com/Movved/PFE-ESTO',
    highlights: ['Espaces administration, enseignants, étudiants et chefs de département', 'Gestion des modules, filières et notes', 'Procès-verbaux et traitement des réclamations', 'Contrôle d’accès et journal d’audit présentés dans le CV'],
    report: {
      intro: 'Chaque acteur d’un établissement a besoin d’une lecture différente des mêmes données. Ce projet de fin d’études organise les interactions entre étudiants, enseignants et administration autour d’un portail Laravel.',
      problem: 'La vie académique combine plusieurs responsabilités : structurer les filières et modules, saisir les notes, permettre leur consultation et traiter les réclamations. Le défi consiste à relier ces opérations tout en distinguant les droits des différents utilisateurs.',
      solution: 'Le portail propose des espaces dédiés. L’administration gère les référentiels et les comptes ; les enseignants retrouvent leurs modules, saisissent les notes et accèdent aux procès-verbaux ; les étudiants consultent leurs résultats et déposent des réclamations. Un espace chef de département complète l’organisation pédagogique.',
      architecture: [
        ['Vues Blade', 'Des écrans rendus par Laravel présentent les tableaux de bord, formulaires et listes adaptés aux espaces du portail.'],
        ['Routes & contrôleurs', 'Les routes sont regroupées par domaine : administration, enseignants, étudiants, département et profil.'],
        ['Modèles Eloquent', 'Les données académiques sont organisées dans une base relationnelle MySQL et manipulées avec l’ORM de Laravel.'],
      ],
      decisions: [
        ['Une application multi-rôles', 'Le CV décrit un contrôle d’accès RBAC strict. Les routes du dépôt montrent les espaces métier et un groupe protégé par authentification ; un audit complet des autorisations n’a pas été effectué pour cette présentation.'],
        ['Accompagner la donnée jusqu’au document', 'La saisie des notes et les routes de procès-verbaux relient les opérations quotidiennes aux documents académiques.'],
        ['Inscrire le travail dans un collectif', 'Le dépôt de référence appartient à Movved et est celui indiqué dans mon CV. Cette réalisation est présentée comme un projet de fin d’études collaboratif.'],
      ],
      outcome: 'Une expérience de conception d’un portail académique, avec plusieurs espaces fonctionnels et des données interdépendantes. Le projet met en relation les modèles, les écrans et les règles d’accès plutôt que de traiter chaque formulaire isolément.',
      boundaries: 'La présentation s’appuie sur le CV et les routes publiques du dépôt ; elle ne revendique ni déploiement public ni nombre d’utilisateurs.',
      steps: [
        { title: 'Organiser', label: 'Administration', text: 'Structurer les filières et les modules et gérer les personnes rattachées à l’établissement.', output: 'Référentiel académique' },
        { title: 'Renseigner', label: 'Enseignant', text: 'Retrouver ses modules, saisir les notes et accéder au procès-verbal associé.', output: 'Notes et procès-verbal' },
        { title: 'Consulter', label: 'Étudiant', text: 'Consulter les résultats et transmettre une réclamation depuis son espace.', output: 'Suivi pédagogique' },
      ],
      sources: [{ label: 'Parcours et routes du portail', path: 'pfe-app/routes/web.php' }, { label: 'Installation du projet', path: 'README.md' }],
    },
  },
  {
    id: 'intern-management', name: 'Gestion des stagiaires', group: 'main', category: 'Application métier', accent: '#74c9b0', visual: 'document',
    tagline: 'Du dossier à l’attestation.', context: 'Stage · DSIC, Préfecture d’Oujda-Angad', period: 'Juin 2025',
    role: 'Développement web · stage', status: 'Déployé durant le stage', technicalFocus: 'Gestion administrative et génération PDF', evidence: 'Informations attestées par le CV',
    description: 'Une application PHP et MySQL de gestion des stagiaires, avec génération automatique d’attestations PDF.',
    stack: ['PHP', 'MySQL', 'PDF'],
    highlights: ['Gestion des stagiaires', 'Stockage relationnel avec MySQL', 'Génération automatique d’attestations PDF', 'Application déployée durant le stage, selon le CV'],
    report: {
      intro: 'Un projet de stage centré sur un besoin administratif concret : gérer les stagiaires et produire les documents qui accompagnent leur passage au sein de la préfecture.',
      problem: 'Le contexte est celui de la DSIC de la Préfecture d’Oujda-Angad. Le besoin présenté dans mon CV associe la gestion des stagiaires à la production d’attestations, deux opérations qui gagnent à utiliser une même source d’information.',
      solution: 'J’ai réalisé un système web en PHP avec une base MySQL et une génération automatique de documents PDF. L’application a été déployée dans le cadre du stage. La présentation se concentre sur ce périmètre attesté par le CV, sans attribuer au projet des modules non documentés.',
      architecture: [
        ['Application PHP', 'Le traitement côté serveur porte les opérations de gestion des stagiaires.'],
        ['Base MySQL', 'Une base relationnelle conserve les informations nécessaires au système de gestion.'],
        ['Attestation PDF', 'La génération automatique fournit le document de sortie du parcours administratif. La bibliothèque utilisée n’est pas précisée dans le CV.'],
      ],
      decisions: [
        ['Partir d’un besoin de terrain', 'Le sujet s’inscrit dans une expérience au sein d’une direction des systèmes d’information, avec une livraison déployée.'],
        ['Relier gestion et génération', 'Les attestations font partie du système de gestion, ce qui donne au parcours une sortie documentaire concrète.'],
      ],
      outcome: 'Cette expérience met en avant la réalisation et le déploiement d’une application administrative en PHP / MySQL, ainsi que l’automatisation d’un document PDF.',
      boundaries: 'Le CV est la source disponible pour ce projet. Aucun dépôt, écran d’origine, schéma de base ou mesure de gain de temps n’a été fourni ; l’aperçu ci-dessous est une illustration du parcours.',
      steps: [
        { title: 'Gérer', label: 'Dossier de stage', text: 'Le système rassemble les informations nécessaires à la gestion des stagiaires.', output: 'Informations du stage' },
        { title: 'Conserver', label: 'MySQL', text: 'Les données sont conservées dans une base relationnelle utilisée par l’application PHP.', output: 'Données enregistrées' },
        { title: 'Générer', label: 'Attestation PDF', text: 'La génération automatique produit une attestation au format PDF.', output: 'Attestation produite' },
      ], sources: [],
    },
  },
  {
    id: 'youtube-downloader', name: 'YouTube Video Downloader', group: 'main', category: 'Web & média', accent: '#f18798', visual: 'video',
    tagline: 'Un lien. Un format. Un flux.', context: 'Projet personnel', period: 'Node.js · Express',
    role: 'Projet personnel', status: 'Code source public', technicalFocus: 'API Express et transmission de flux HTTP', evidence: 'Serveur et interface publics inspectés',
    description: 'Une interface de téléchargement qui récupère les informations d’une vidéo et propose plusieurs options de qualité.',
    stack: ['JavaScript', 'Node.js', 'Express', '@distube/ytdl-core', 'HTML / CSS'], github: 'https://github.com/ibrahim11-dv/YoutubeVideosDownloader', branch: 'master',
    highlights: ['Aperçu du titre, de la miniature et de la durée', 'Sélection de qualités vidéo et option audio', 'API /info et /download', 'Transmission du flux vers la réponse HTTP'],
    report: {
      intro: 'Ce projet explore un parcours web court : coller une URL, identifier la vidéo, choisir une option puis demander son téléchargement.',
      problem: 'L’interface doit rendre compréhensible une opération qui dépend de métadonnées et de flux distants. Le projet sépare la découverte d’une vidéo de la demande de téléchargement afin de proposer un aperçu avant l’action.',
      solution: 'Une page HTML / CSS / JavaScript interroge un serveur Express. L’API /info utilise ytdl-core pour récupérer les métadonnées ; l’interface en affiche le titre, la durée et la miniature. La route /download sélectionne une qualité, prépare le nom du fichier et transmet le flux dans la réponse HTTP.',
      architecture: [
        ['Interface navigateur', 'Saisie d’URL, choix du format, aperçu et retour visuel de chargement sont réalisés en JavaScript natif.'],
        ['API Express', 'Deux routes distinctes servent les métadonnées et le téléchargement ; les erreurs de récupération produisent une réponse HTTP 400.'],
        ['Flux ytdl-core', 'La bibliothèque @distube/ytdl-core fournit les informations et les flux. Le serveur les transmet avec pipe(res).'],
      ],
      decisions: [
        ['Prévisualiser avant de télécharger', 'Le titre et la durée permettent de reconnaître le contenu demandé avant de lancer le transfert.'],
        ['Transmettre le flux', 'Le serveur raccorde le flux à la réponse HTTP ; le code ne construit pas d’archive locale des vidéos téléchargées.'],
        ['Identifier les limites des formats', 'Le choix nommé MP3 demande un flux audio sans transcodage explicite. Certaines qualités vidéo utilisent des flux séparés ; le dépôt ne montre pas de fusion audio/vidéo.'],
      ],
      outcome: 'Le projet met en pratique les appels asynchrones depuis une interface, une petite API Express et la transmission de flux. La fiche permet d’explorer ce parcours sans appeler YouTube ni lancer de téléchargement.',
      boundaries: 'La disponibilité réelle dépend des formats proposés et du service distant. L’aperçu du portfolio est illustratif et ne valide pas le fonctionnement actuel du téléchargement.',
      steps: [
        { title: 'Identifier', label: 'GET /info', text: 'Une URL est envoyée au serveur pour récupérer les métadonnées de la vidéo.', output: 'Titre · durée · miniature' },
        { title: 'Choisir', label: 'Qualité vidéo ou audio', text: 'L’interface propose plusieurs résolutions et une option audio. Leur disponibilité dépend de la vidéo.', output: 'Option sélectionnée' },
        { title: 'Transmettre', label: 'GET /download', text: 'Express prépare la réponse de téléchargement et y transmet le flux sélectionné.', output: 'Flux HTTP' },
      ], sources: [{ label: 'Serveur et routes', path: 'server.js' }, { label: 'Interface et parcours', path: 'public/index.html' }],
    },
  },
  {
    id: 'learnxcompile', name: 'LearnXcompile', group: 'main', category: 'À découvrir', accent: '#83bafa', visual: 'code',
    tagline: 'Une nouvelle réalisation à découvrir.', context: 'Projet principal', period: 'Présentation en préparation',
    role: 'Projet principal', status: 'Documentation en cours', technicalFocus: 'Informations techniques à compléter', evidence: 'Aucune documentation source fournie à ce jour',
    description: 'La présentation détaillée de LearnXcompile sera ajoutée avec la documentation du projet.',
    stack: [], highlights: [], pending: true,
  },
  {
    id: 'minichat', name: 'MiniChat', group: 'other', category: 'Temps réel', accent: '#bea1ef', visual: 'chat',
    tagline: 'Une conversation, sans rechargement.', context: 'Projet personnel', period: 'React · Socket.io',
    role: 'Projet personnel', status: 'Code source public', technicalFocus: 'Événements temps réel avec Socket.io', evidence: 'Client et serveur publics inspectés',
    description: 'Une messagerie React avec un serveur Node.js et des échanges événementiels via Socket.io.',
    stack: ['React', 'JavaScript', 'Node.js', 'Express', 'Socket.io', 'Vite'], github: 'https://github.com/ibrahim11-dv/MiniChatApp-using-socket.io', branch: 'master',
    highlights: ['Émission et réception d’événements Socket.io', 'Messages envoyés et reçus distingués dans l’interface', 'Horodatage côté client', 'Client React et serveur Node.js séparés'],
    report: {
      intro: 'MiniChat explore les échanges en temps réel avec une interface volontairement centrée sur la conversation.',
      problem: 'Une conversation doit afficher les nouveaux messages sans demander au visiteur de recharger la page. Ce projet met en relation la gestion d’état React avec un serveur qui diffuse des événements.',
      solution: 'Le client émet send-message lorsqu’un message est envoyé et l’ajoute à son état local. Le serveur reçoit cet événement puis diffuse receive-message aux autres connexions. Les messages entrants enrichissent la liste React avec leur auteur d’affichage et un horodatage local.',
      architecture: [['Client React', 'Un formulaire contrôlé et une liste de messages gèrent la saisie et l’affichage.'], ['Serveur Node.js', 'Express et un serveur HTTP hébergent Socket.io.'], ['Événements Socket.io', 'socket.broadcast.emit transmet le message aux autres clients connectés.']],
      decisions: [['Retour immédiat', 'Le message envoyé apparaît localement sans attendre sa rediffusion par le serveur.'], ['Cycle de vie des abonnements', 'Le composant enregistre son écouteur dans useEffect et le retire au nettoyage avec socket.off.'], ['Périmètre du prototype', 'Le code inspecté ne propose ni comptes utilisateurs, ni salons privés, ni persistance des conversations.']],
      outcome: 'Un exemple concret de synchronisation entre une interface React et des événements réseau, avec une séparation lisible entre client et serveur.',
      boundaries: 'Les messages sont conservés dans l’état du client ; l’aperçu ci-dessous ne connecte pas deux visiteurs réels.',
      steps: [{ title: 'Écrire', label: 'Client React', text: 'Le formulaire prépare un message et l’affiche côté émetteur.', output: 'send-message' }, { title: 'Diffuser', label: 'Serveur Socket.io', text: 'Le serveur relaie le message aux autres connexions.', output: 'socket.broadcast.emit' }, { title: 'Recevoir', label: 'Autre client', text: 'La liste React accueille le message reçu et son horodatage.', output: 'receive-message' }],
      sources: [{ label: 'Événements serveur', path: 'server/index.js' }, { label: 'Interface React', path: 'client/src/App.jsx' }],
    },
  },
  {
    id: 'exercise-tracker', name: 'Exercise Tracker', group: 'other', category: 'API', accent: '#9fce83', visual: 'activity',
    tagline: 'Des activités, un historique.', context: 'Parcours freeCodeCamp', period: 'Back End Development and APIs',
    role: 'Projet de formation', status: 'Code source public', technicalFocus: 'API REST, middlewares et historique filtré', evidence: 'Code source public inspecté',
    description: 'Une API pour enregistrer des utilisateurs, ajouter leurs exercices et consulter un historique filtré.',
    stack: ['Node.js', 'Express', 'API REST'], github: 'https://github.com/ibrahim11-dv/exerciceTracker-freeCodeCamp_',
    highlights: ['Création et liste des utilisateurs', 'Enregistrement d’exercices datés', 'Filtres from, to et limit sur l’historique', 'Réponses JSON structurées'],
    report: {
      intro: 'Exercise Tracker transforme un carnet d’activités en ressources accessibles par une API : utilisateurs, exercices et historique.',
      problem: 'Le projet du parcours backend freeCodeCamp demande de rattacher des exercices à un utilisateur et de retrouver un journal exploitable. Le périmètre associe création de données, dates et filtres de consultation.',
      solution: 'Les routes Express exposent la création d’utilisateurs et d’exercices ainsi que la consultation des journaux. Des middlewares réalisent la recherche et la préparation des documents ; les gestionnaires de routes assemblent ensuite les réponses JSON.',
      architecture: [['Routes REST', 'GET et POST organisent les opérations autour de /api/users et des exercices associés.'], ['Middlewares', 'Des fonctions dédiées retrouvent l’utilisateur, créent un exercice et filtrent les documents du journal.'], ['Réponse JSON', 'L’historique renvoie l’identité, les filtres utilisés, le nombre de résultats et la liste des activités.']],
      decisions: [['Des ressources explicites', 'Le chemin d’un exercice inclut l’identifiant de l’utilisateur auquel il appartient.'], ['Un historique filtrable', 'Les paramètres from, to et limit permettent de cibler une partie du journal.'], ['Des dates présentables', 'La réponse formate les dates avec toDateString pour le contrat attendu par le projet freeCodeCamp.']],
      outcome: 'Ce projet illustre la conception d’endpoints, l’enchaînement de middlewares et la construction de réponses adaptées à un contrat d’API.',
      boundaries: 'La fiche décrit les routes du dépôt. Aucun résultat de charge ni service public actif n’est présenté.',
      steps: [{ title: 'Créer', label: 'POST /api/users', text: 'Créer un utilisateur et récupérer son identifiant.', output: 'username + _id' }, { title: 'Enregistrer', label: 'POST …/exercises', text: 'Associer une description, une durée et une date à cet utilisateur.', output: 'Exercice enregistré' }, { title: 'Filtrer', label: 'GET …/logs', text: 'Consulter les activités en précisant une période ou une limite.', output: 'count + log' }], sources: [{ label: 'Routes et réponses JSON', path: 'index.js' }],
    },
  },
  {
    id: 'url-shortener', name: 'URL Shortener', group: 'other', category: 'API', accent: '#79c9d6', visual: 'link',
    tagline: 'Une longue adresse. Un court chemin.', context: 'Parcours freeCodeCamp', period: 'Back End Development and APIs',
    role: 'Projet de formation', status: 'Code source public', technicalFocus: 'Validation d’URL et redirection HTTP', evidence: 'Code source public inspecté',
    description: 'Un microservice Express qui attribue un identifiant à une URL puis redirige vers son adresse d’origine.',
    stack: ['Node.js', 'Express', 'JavaScript'], github: 'https://github.com/ibrahim11-dv/url-shortening',
    highlights: ['Analyse des URL avec le constructeur URL', 'Protocoles HTTP et HTTPS autorisés', 'Identifiants numériques courts', 'Redirection vers l’adresse enregistrée'],
    report: {
      intro: 'Un petit service pour explorer le cycle complet d’une URL courte : validation, association d’un identifiant puis redirection.',
      problem: 'Une adresse peut être longue, mais son point d’entrée peut être réduit à un identifiant. Le projet consiste à maintenir cette correspondance et à refuser les entrées qui ne sont pas des URL HTTP ou HTTPS valides.',
      solution: 'La route POST /api/shorturl analyse l’adresse avec le constructeur URL, vérifie son protocole et lui attribue un compteur numérique. La route GET correspondante recherche cette association puis utilise la redirection Express pour rejoindre la destination.',
      architecture: [['Entrée HTTP', 'Express accepte les formulaires et le JSON contenant l’URL à raccourcir.'], ['Association en mémoire', 'Un objet JavaScript associe chaque compteur à l’adresse d’origine.'], ['Redirection', 'La route de consultation appelle res.redirect ou retourne une erreur JSON pour un identifiant inconnu.']],
      decisions: [['Valider avant de stocker', 'L’analyse syntaxique et le contrôle du protocole précèdent la création de l’identifiant.'], ['Garder le mécanisme lisible', 'Le compteur et la table en mémoire rendent visible le principe d’un raccourcisseur d’URL.'], ['Assumer la durée de vie', 'Le stockage est en mémoire : les liens ne persistent pas après un redémarrage du serveur. Une persistance durable serait une évolution.']],
      outcome: 'Une mise en pratique compacte de la validation d’entrée, des réponses JSON et des redirections HTTP, avec un compromis de stockage clairement identifié.',
      boundaries: 'Le service inspecté ne comporte pas de base persistante ni de système de comptes. La visualisation utilise une adresse fictive réservée aux exemples.',
      steps: [{ title: 'Valider', label: 'HTTP ou HTTPS', text: 'Analyser l’URL et vérifier que son protocole est pris en charge.', output: 'URL acceptée' }, { title: 'Associer', label: 'POST /api/shorturl', text: 'Attribuer un identifiant numérique et conserver la correspondance en mémoire.', output: 'short_url: 1' }, { title: 'Rediriger', label: 'GET /api/shorturl/1', text: 'Retrouver la destination et retourner une redirection HTTP.', output: 'Adresse d’origine' }], sources: [{ label: 'Validation, stockage et redirection', path: 'index.js' }],
    },
  },
];

export function projectMarkdown(project) {
  const report = project.report;
  return `# ${project.name}\n\n${project.description}\n\n${project.context} · ${project.period}\n\n${report ? [
    `## Contexte\n${report.intro}\n\n${report.problem}`,
    `## Solution\n${report.solution}`,
    `## Technologies\n${project.stack.join(' · ')}`,
    `## Architecture\n${report.architecture.map(([title, text]) => `### ${title}\n${text}`).join('\n\n')}`,
    `## Parcours\n${report.steps.map((step, index) => `${index + 1}. ${step.title} — ${step.text}`).join('\n')}`,
    `## Choix de conception\n${report.decisions.map(([title, text]) => `### ${title}\n${text}`).join('\n\n')}`,
    `## Bilan\n${report.outcome}\n\n${report.boundaries}`,
  ].join('\n\n') : 'Présentation détaillée en préparation.'}\n\n## Sources\n${project.pending ? 'Documentation du projet en attente.' : project.github || 'CV d’Ibrahim Chehlafi'}\n`;
}
