export const PROJECT_PRESENTATION = {
  parcvision: { problem: 'Relier les opérations d’une flotte à ses documents.', contribution: 'Développement full-stack dans le cadre du stage chez ZAI-CONCEPT INFO.', decision: 'Séparer interface, services métier et persistance ; indexer les archives par OCR.', result: 'Gestion de flotte, archivage consultable et cartographie avec GPS simulé.', flow: ['Véhicule + conducteur', 'Mission et carte simulée', 'Archive OCR consultable'] },
  'pfe-esto': { problem: 'Relier notes, modules et suivi pédagogique entre plusieurs rôles.', contribution: 'Projet de fin d’études collaboratif, référencé dans le CV.', decision: 'Organiser les espaces par rôle autour des données académiques.', result: 'Portail académique avec notes, procès-verbaux et réclamations.', flow: ['Administration / département', 'Enseignant : notes', 'Étudiant : résultats'] },
  'intern-management': { problem: 'Gérer les dossiers de stage et produire les attestations.', contribution: 'Développement PHP / MySQL durant le stage à la DSIC.', decision: 'Relier les données administratives à la génération de documents PDF.', result: 'Application déployée pendant le stage, selon le CV.', flow: ['Dossier de stage', 'Base MySQL', 'Attestation PDF'] },
  'youtube-downloader': { problem: 'Choisir un format à partir des métadonnées d’une vidéo.', contribution: 'Projet personnel avec interface JavaScript et API Express.', decision: 'Séparer les métadonnées du téléchargement et transmettre le flux HTTP.', result: 'Parcours URL, aperçu, sélection et transmission du flux ; limites décrites ci-dessous.', flow: ['URL → métadonnées', 'Sélection du format', 'Flux HTTP'] },
  minichat: { problem: 'Recevoir des messages sans recharger la page.', contribution: 'Projet personnel React, Node.js et Socket.io.', decision: 'Diffuser les événements aux autres connexions avec Socket.io.', result: 'Prototype de messagerie ; conversations conservées dans l’état du client.', flow: ['Client : send-message', 'Serveur : broadcast', 'Client : receive-message'] },
  'exercise-tracker': { problem: 'Associer des exercices à un utilisateur et consulter son journal.', contribution: 'Projet du parcours backend freeCodeCamp.', decision: 'Organiser l’API en ressources et filtrer le journal par date et limite.', result: 'API de création d’utilisateurs, d’exercices et de consultation JSON.', flow: ['POST /api/users', 'POST …/exercises', 'GET …/logs → JSON'] },
  'url-shortener': { problem: 'Associer une adresse longue à une entrée courte.', contribution: 'Microservice réalisé dans le parcours freeCodeCamp.', decision: 'Valider HTTP/HTTPS avant d’attribuer une clé en mémoire.', result: 'Création de liens courts et redirection ; stockage non persistant.', flow: ['URL HTTP(S) validée', 'Clé courte en mémoire', 'Recherche → redirection'] },
};
